### ISSUE TITLE
InstantTracker fails to adjust model position

### ISSUE THREAD

**Issue by shiruken1** [zappar-xr/zappar-react-three-fiber#34]
**Describe the bug**
  InstantTracker will not adjust model position once the camera moves, after object is "placed".

**To Reproduce**
1. Clone react-three-example-instant-tracking-cube, install and start
2. Open page on mobile device.
3. Click on "Tap here to place the object"
4. Move camera

**Expected behavior**
Expected the model to be rendered at a different position once the camera moved.

**Desktop and smartphone**
 - OS: Android & ElementaryOS
 - Browser Brave
 - Version 1.31.88

**Comment by cc-steina** [comment]
Hey there! I know this is an old issue but the newest patch (at the time of writing 1.2.6) might have a fix in it that resolved a similar issue my team had. You should try updating the package if this is still relevant to you otherwise I think this ticket could get closed by a mod/dev.
