### ISSUE TITLE
Hi Nyan,

### ISSUE THREAD

**Issue by anjali14garg** [zappar-xr/zappar-react-three-fiber#43]
Hi Nyan,

After adding  HTTPS=true react-app-rewired start in package.json facing issue of **'HTTPS' is not recognized as an internal or external command,** .
After searching solution for it i got solution on https://stackoverflow.com/questions/60374269/https-is-not-recognized-as-an-internal-or-external-command.
But still getting issues. Can you plese check once again. on same url  https://github.com/anjali14garg/zappertest

_Originally posted by @anjali14garg in https://github.com/zappar-xr/zappar-react-three-fiber/issues/42#issuecomment-1067900359_

**Comment by nyan-left** [comment]
See my reply in the original issue: https://github.com/zappar-xr/zappar-react-three-fiber/issues/42#issuecomment-1067912893
