### ISSUE TITLE
When I start the camera on a iOS17 pro device, it becomes a telephoto lens

### ISSUE THREAD

**Issue by activeguild** [zappar-xr/zappar-react-three-fiber#90]
**Describe the bug**
If it is a pro, the standard rear triple camera should be used, but it would be a telephoto.
Any tips or workaround?

**To Reproduce**
1. Use React's ZapparCamera component to activate the camera.

**Expected behavior**
To be activated with a standard magnification lens, not a telephoto lens.

**Smartphone (please complete the following information):**
 - Device: iPhone 12(13,14,15) pro
 - OS: iOS17
 - Browser [chrome, safari]

**Comment by activeguild** [comment]
The order in which navigator.mediaDevices.enumerateDevices() can be retrieved seems to have changed in iOS17.

**Comment by nyan-left** [comment]
Hi @activeguild ,

Could you please confirm which version of zappar r3f SDK you're using? Versions `2.4.9` and `3.0.0-beta.4` should have iOS 17 issues addressed.

**Comment by activeguild** [comment]
Thanks @nyan-left 


The following error occurs when updating to the latest version.
The development environment is using [vite](https://ja.vitejs.dev/).

Do you have any tips on how to solve this problem?

```
Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 0: 
expected a module of at least 8 bytes (evaluating 'new WebAssembly.Module(c)')
```

**Comment by nyan-left** [comment]
Please may you try configuring vite as so:
https://github.com/zappar-xr/zappar-react-three-fiber-examples/issues/2#issuecomment-1580759442

A minimal repo reproducing this issue would also be very handy! :)

**Comment by activeguild** [comment]
It did not work even with the configuration you suggested.
Prepare a reproducible repository.

**Comment by nyan-left** [comment]
Hi @activeguild ,
Here's a working template using r3f, vite, ts

https://github.com/nyan-left/uar-r3f-vite-ts-ft/tree/main
